# application config

spring:
  application:
    name: "spring-cloud-function-aws-basic"

spring.cloud.function:
  definition: "uppercase"

logging:
    level:
        root: info
        '[com.kapresoft]': warn
        '[org.springframework]': warn
